### ISSUE TITLE
Nebulosity values are strange

### ISSUE THREAD

**Issue by supermamie** [SimonMellerin/Pilea#16]
I have some problems with the nebulosity values.

The values are either empty, or > 80%, some time even > 100% (I have a 100.3%, followed by an empty day).

Even days when I can only see very few clouds, the value is > 80%, and when I can not see any cloud, there is no value.

![image](https://user-images.githubusercontent.com/693751/53162535-84da2480-35cc-11e9-8931-f04ad5b9fd3f.png)

**Comment by SimonMellerin** [comment]
It could come from the MeteoFrance Feed I've never experience this for Nantes-Bouguenais
Which station do you use ?

**Comment by SimonMellerin** [comment]
Hum ok, I've just checked, I've some weird values too :/

And looking at files coming from MeteoFrance, for yesterday, I've a value at 103 (?)

**Comment by SimonMellerin** [comment]
Well, maybe they have some problems with their sensors...

**Comment by supermamie** [comment]
I'm using Toulouse Blagnac station.
How can I try to debug this (and maybe find some doc/infos on those values ? )

**Comment by SimonMellerin** [comment]
everything is here : https://donneespubliques.meteofrance.fr/?fond=produit&id_produit=90&id_rubrique=32

There're one file each 3h, I only keep a value per day. For nebulosity, I average.

**Comment by SimonMellerin** [comment]
Since the problem comes from  MeteoFrance, I'm gonna close this one
