### ISSUE TITLE
Error at install with sqlite database

### ISSUE THREAD

**Issue by zezinho42** [SimonMellerin/Pilea#19]
Here is the Doctrine error I get :+1: 
``Pilea installer
===============

Step 1 of 3: Checking system requirements.
------------------------------------------

 --------------------- -------- ---------------- 
  Checked               Status   Recommendation  
 --------------------- -------- ---------------- 
  Database connection   OK!                      
  Database version      OK!                      
 --------------------- -------- ---------------- 

 Success! Seems that your system can run pilea properly.

Step 2 of 3: Setting up database.
---------------------------------

09:20:26 ERROR     [console] Error thrown while running command "pilea:install". Message: "Call to undefined method Doctrine\ORM\EntityManager::get()" ["exception" => Error { …},"command" => "pilea:install","message" => "Call to undefined method Doctrine\ORM\EntityManager::get()"]

In InstallCommand.php line 286:
                                                                                                                                    
  Attempted to call an undefined method named "get" of class "Doctrine\ORM\EntityManager".                                          
  Did you mean to call e.g. "getCache", "getClassMetadata", "getConfiguration", "getConnection", "getEventManager", "getExpression  
  Builder", "getFilters", "getHydrator", "getMetadataFactory", "getPartialReference", "getProxyFactory", "getReference", "getRepos  
  itory" or "getUnitOfWork"?

**Comment by SimonMellerin** [comment]
I delete unnecessary (and broken) code which was triggering only for SQLite.

Let me know if you succeed to use Pilea with SQlite, I've never tried

**Comment by zezinho42** [comment]
> I deleted unnecessary (and broken) code which was triggering only for SQLite.
Thanks, it worked.

> Let me know if you succeed to use Pilea with SQlite, I've never tried
I am now stuck with the question : where to put the Enedis login?
For now there http script index.php tries to use more than 512M, is it normal for you?

**Comment by SimonMellerin** [comment]
Which server do you use ? Nginx ? Web Server Bundle ?

**Comment by zezinho42** [comment]
I use apache with mod_php. For now I only get a blank page, even if I allow 1024M as maximum memory size. Looks like some thing is eating all memory. Can you just confirm me that you don't need as much memory in your system?

**Comment by SimonMellerin** [comment]
Yes I can confirm you Pilea shouldn't need as mush memory !
specially if you don't have any configuration to your linky account yet
