### ISSUE TITLE
daily consumption = -1kwh

### ISSUE THREAD

**Issue by ggekiere** [SimonMellerin/Pilea#21]
Hi,

I updated to version 0.3.7 last saturday. Since then, my daily consumption appears to be minus 1 kwh. No problem on enedis data's side.

Pilea is installed on my yunohost instance (version 3.6.4.6).

Please tell me if you need more information (log or anything?).

Thanks!

Geoffrey.

**Comment by SimonMellerin** [comment]
Hi,

I think this issue is a side effect of the correction of this one: https://github.com/YunoHost-Apps/pilea_ynh/issues/7

I'm gonna check that next week but first of all, can you try to go to Enedis website and check if you can see it overthere.

(what's weird is that it seems to work well on my instance :/)
simon

**Comment by ggekiere** [comment]
Hi!
I'm not quite sure of what you mean by "it"? My consumption appears on enedis website (if that's what you want me to check? :) ).
Regards,
Geofffrey.

**Comment by SimonMellerin** [comment]
hi

yes it wasn't very clear indeed..
but yes I wanted you to check if your consumption was ok in the enedis website.

**Comment by supermamie** [comment]
On my side, it is OK on enedis, but -1kwh in pilea

**Comment by SimonMellerin** [comment]
Do one of you have something in logs  

- from Yunohost BO (url: '/yunohost/admin/#/apps/pilea/debug')
- or from Symfony logs in /var/www/pilea/var/log/ folder

**Comment by ggekiere** [comment]
Here we go:

- in [/var/log/nginx/access.log](https://paste.yunohost.org/ayucokased.sm)

- in [/var/log/nginx/error.log](https://paste.yunohost.org/zijivemena.vbs)

- in [/var/www/pilea/var/log/prod-2019-08-26.log](https://paste.yunohost.org/ewaxanogaw.vbs)

**Comment by supermamie** [comment]
I just had 3 upgrades of Pilea on my YunoHost instance, without any improvements on this bug, any news ?

**Comment by SimonMellerin** [comment]
Sorry, I checked on ggekiere logs but can't found any reason why it won't work for both of you
I didn't succeed in reproducing it on a VM or on my own instance.

All yours consumptions are -1, event month and year consumptions ?
Are the meteo data ok ?

**Comment by supermamie** [comment]
In the daily view, I have -1 every day since August 1st.
In weekly view, I can not see the value, but it is negative.
In monthly view I have a positive value for August and September, so I think some correct values are stored somewhere in database.

The weather seems correct.
For the nebulosity, I have again some empty values after August 1st (before that, it was displayed as 0%, but I think this was done by an upgrade script)

**Comment by SimonMellerin** [comment]
Huum, weekly value is calculated but monthly data come from Enedis so I suspect Enedis API behavior to have change.

Before, when Pilea tries to get data but it's too early in the day and there's nothing, Enedis returned nothing. Maybe now it returns -1 which Pilea considers as a correct value since it's something !

to be sure can you launch this SQL query ?

`delete from data_value join feed_data on feed_data.id = data_value.feed_data_id where data_value.value = '-1' and feed_data.data_type like "CONSO_ELEC"`

This will destroy all '-1' values in your database, after that, pilea will try to get fresh ones, if my hypothesis is right, you should get correct data

**Comment by supermamie** [comment]
Lines removed.
Now I have yesterday value, nothing for the other 38 days removed.

**Comment by supermamie** [comment]
Just to try, I launched this command
> sudo -u pilea php7.2 /var/www/pilea/bin/console pilea:fetch-data force 2019-09-07 -vvv

-vvv did not create any log :( (and now I have one more day in the logs)

**Comment by SimonMellerin** [comment]
well, it partially confirms my hypothesis.

Just to be sure, before you removed lines, you have no hourly and no daily data ?

**Comment by supermamie** [comment]
No, I have this data for the 2 days manually added, but not for others where the daily consumption is -1 

![image](https://user-images.githubusercontent.com/693751/64546554-33587380-d32b-11e9-8fff-28307050cfb9.png)

**Comment by SimonMellerin** [comment]
Can you try to update pilea_ynh with the 'fix-linky-fetching' branch ?
Then launch 
`delete from data_value join feed_data on feed_data.id = data_value.feed_data_id where data_value.date < '2019/09/01' and feed_data.data_type like "CONSO_ELEC"`

To delete broken data, it should redownload all your data and don't accept -1 values

**Comment by supermamie** [comment]
I changed the SQL request to delete every CONSO_ELEC after August 1st instead of before september 1, to avoid deleting EVERYTHING.
Then waited 10min and I only have yesterday data received.

**Comment by SimonMellerin** [comment]
Holy shit, sorry for the wrong sql query...

You updated your instance with the '[fix-linky-fetching](https://github.com/YunoHost-Apps/pilea_ynh/tree/fix-linky-fetching)' branch ?

**Comment by SimonMellerin** [comment]
Arrg my push failed yesterday.. can you retry ?

**Comment by supermamie** [comment]
I ran this command for the update :
`sudo yunohost app upgrade pilea -u https://github.com/YunoHost-Apps/pilea_ynh/tree/fix-linky-fetching --debug`
(the command to test from another branch is frequently displayed in the readme of yunohost packages, so I used it from nextcloud_ynh).

I just read your new message.
Update in progress, result in ~10min

**Comment by supermamie** [comment]
SQL error during the update on :
```
   An exception occurred while executing '
               DELETE FROM data_value
               JOIN feed_data ON feed_data.id = data_value.feed_data_id
               WHERE data_value.value = "-1"
               AND feed_data.data_type LIKE "CONSO_ELEC"
           ':
```

note : I had this error while executing your request too, so I adapted them every time to remove the JOIN and directly remove when the type is 1 (which is CONSO_ELEC in my case)

**Comment by supermamie** [comment]
Note 2 : I have MariaDB and not MySQL, if this can help...

**Comment by supermamie** [comment]
And the request modified which seems to work :
`delete data_value.* from data_value join feed_data on feed_data.id = data_value.feed_data_id where data_value.value = '-1' and feed_data.data_type like "CONSO_ELEC";`

(but I have zero rows affected because I already deleted -1 values)

**Comment by SimonMellerin** [comment]
should be ok, this time I've tested before...

**Comment by supermamie** [comment]
Update successfull, but I still have only yesterday data.
I tried to do `delete from data_value WHERE date > '2019/08/01' AND feed_data_id = '1';` and it affected 27 rows :scream: 
[10min after]
Yesterday data re-appeared, but only this day, not the days before.

**Comment by SimonMellerin** [comment]
Well I'm sorry, I'm doing 2 things at the same time and I do it too quickly..

Should be right if you retry to update from 'fix-linky-fetching' branch and then delete data as before

Sorry ! I swear this time it should be good !

**Comment by supermamie** [comment]
Sorry but 10 min after the update, even yesterday data were not back 🙁

**Comment by supermamie** [comment]
3 hours later, it's all here, I should gave been more patient 👍

**Comment by SimonMellerin** [comment]
In a couple of days, can you tell me if the fix I made avoid you to have -1kwh ?
If so, i'm gonna push this version to master branch of pilea_ynh package

Cheers

**Comment by supermamie** [comment]
So far so good 🙂

**Comment by SimonMellerin** [comment]
Ok thanks !
