### ISSUE TITLE
Password field appears empty

### ISSUE THREAD

**Issue by JocelynDelalande** [SimonMellerin/Pilea#3]
If I fill the linky password field and submit

It displays me back the form with empty password field, that is unexpected.

**Comment by SimonMellerin** [comment]
It's default behavior of Symfony form.
When you go back to a form with password, password is empty.

But I suppose can add a success message to disambiguate. 
I need to update this form anyway: for now, there's no proper validation on Linky form (I mean, I don't check that the connection to Enedis works)

**Comment by JocelynDelalande** [comment]
That is a bit different from regular app password form, as this is something we store as-is, without hashing. Regular password forms are probably empty because password is not stored cleartext.

That feedback may seem a bit nitpicked, just take it as a surprised user feedback (I thought at first I forgot to enter the password or a bug prevented it from being saved).

> I need to update this form anyway: for now, there's no proper validation on Linky form (I mean, I don't check that the connection to Enedis works)

:+1:
