### ISSUE TITLE
Graph display issues with smartphone

### ISSUE THREAD

**Issue by Krakinou** [SimonMellerin/Pilea#4]
There are some display issues when displaying on a smartphone :
- Date selection is not properly displayed:
![screenshot_20181227-184457_firefox](https://user-images.githubusercontent.com/9308214/50489460-0f0c6f00-0a08-11e9-8a51-a508591042a8.jpg)
- The tooltip for the second menu make it nearly non clickable:
2nd menu:
![screenshot_20181227-184534_firefox](https://user-images.githubusercontent.com/9308214/50489524-63afea00-0a08-11e9-8e82-84866d917eb3.jpg)
3rd menu:
![screenshot_20181227-184603_firefox](https://user-images.githubusercontent.com/9308214/50489533-79bdaa80-0a08-11e9-8512-e6f442864a8d.jpg)
- Once I accessed pilea from smartphone once, all "weekly brick" graphes became veeeeeeery long, even on my desktop:
![image](https://user-images.githubusercontent.com/9308214/50489561-a83b8580-0a08-11e9-9197-7f7b3894c283.png)

**Comment by Krakinou** [comment]
Sorry for the huge screenshot...

**Comment by SimonMellerin** [comment]
Thanks for your feedback

I've not developed a mobile version for now that's why it's a bit ugly sorry, it's in my todo list ;)
the very long heatmap in homepage is due to a bug i have corrected yet. I'm gonna release the fix next week !
