### ISSUE TITLE
No DJU update

### ISSUE THREAD

**Issue by Krakinou** [SimonMellerin/Pilea#6]
DJU are not updating sing Nov 24th.
Maybe related to the log data in #5?
Do you need any more logs?

**Comment by SimonMellerin** [comment]
Hi @Krakinou,

Do you have does your app update temperature ? DJU are calculated from temperature values.

Reading my code, DJU can be NULL only if there's no temperature value to calculate it. In otherway, pilea shouldn't crash f there's no temperature value available... I'm gonna correct this.

**Comment by Krakinou** [comment]
As a matter of fact, there are no meteo update at all since 24/12

**Comment by SimonMellerin** [comment]
hum :confused: 

can you send me last log lines you have ?

Can you try to update your pilea app (I've updated the ynh package) and tell me if it's better !

**Comment by Krakinou** [comment]
I updated this week end and after a few hours (I imagine so that the update run), it's all there now!
Thanks for your help and great work!
